import Head from "next/head";
import Carousal from "../components/home/Carousal";
import Hero from "../components/home/Hero";
import Stats from "../components/home/Stats";
import Testimonials from "../components/home/Testimonials";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="d bg-zinc-100">
        <Navbar />
        <Hero />
        <Carousal />
        <Stats />
        {/* Donation */}
        <Testimonials />
        {/* Team */}
        {/* Contacts? */}
      </main>

      <Footer />
    </>
  );
}
